<?xml version="1.0" encoding="utf-8"?><Database Name="PainClinic" Class="PainClinicERDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-P7TK3E5\SQLEXPRESS;Initial Catalog=PainClinic;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PainClinicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Addresses" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StreetAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="Address_Clinic" Member="Clinics" ThisKey="AddressId" OtherKey="AddressId" Type="Clinic" />
      <Association Name="Address_Patient" Member="Patients" ThisKey="AddressId" OtherKey="AddressId" Type="Patient" />
    </Type>
  </Table>
  <Table Name="dbo.ClinicDirectory" Member="ClinicDirectories">
    <Type Name="ClinicDirectory">
      <Column Name="ProviderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClinicId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Clinic_ClinicDirectory" Member="Clinic" ThisKey="ClinicId" OtherKey="ClinicId" Type="Clinic" IsForeignKey="true" />
      <Association Name="Patient_ClinicDirectory" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" />
      <Association Name="Provider_ClinicDirectory" Member="Provider" ThisKey="ProviderId" OtherKey="ProviderId" Type="Provider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clinics" Member="Clinics">
    <Type Name="Clinic">
      <Column Name="ClinicId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClinicName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Clinic_ClinicDirectory" Member="ClinicDirectories" ThisKey="ClinicId" OtherKey="ClinicId" Type="ClinicDirectory" />
      <Association Name="Clinic_Provider" Member="Providers" ThisKey="ClinicId" OtherKey="ClinicId" Type="Provider" />
      <Association Name="Address_Clinic" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DailyLogs" Member="DailyLogs">
    <Type Name="DailyLog">
      <Column Name="DailyLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TodaysDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PainRating" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PainLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AmountOfSleep" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ActivityLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DailyActivities" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DailyLog_LogNote" Member="LogNotes" ThisKey="DailyLogId" OtherKey="DailyLogId" Type="LogNote" />
      <Association Name="Patient_DailyLog" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogNotes" Member="LogNotes">
    <Type Name="LogNote">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DailyLogId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DailyLog_LogNote" Member="DailyLog" ThisKey="DailyLogId" OtherKey="DailyLogId" Type="DailyLog" IsForeignKey="true" />
      <Association Name="Patient_LogNote" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patients" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RxReceived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Patient_ClinicDirectory" Member="ClinicDirectories" ThisKey="PatientId" OtherKey="PatientId" Type="ClinicDirectory" />
      <Association Name="Patient_DailyLog" Member="DailyLogs" ThisKey="PatientId" OtherKey="PatientId" Type="DailyLog" />
      <Association Name="Patient_LogNote" Member="LogNotes" ThisKey="PatientId" OtherKey="PatientId" Type="LogNote" />
      <Association Name="Address_Patient" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Providers" Member="Providers">
    <Type Name="Provider">
      <Column Name="ProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prefix" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RxReceived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ClinicId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Provider_ClinicDirectory" Member="ClinicDirectories" ThisKey="ProviderId" OtherKey="ProviderId" Type="ClinicDirectory" />
      <Association Name="Clinic_Provider" Member="Clinic" ThisKey="ClinicId" OtherKey="ClinicId" Type="Clinic" IsForeignKey="true" />
    </Type>
  </Table>
</Database>